

-- ITEM TABLE
INSERT INTO ITEM(ID_ITEM, NAME, DESCRIPTION, PRICE_TO_BUY, PRICE_TO_SELL)
SELECT
    TO_NUMBER(ID),
    NAME,
    DESCRIPTION,
    TO_NUMBER(PRICE_TO_BUY),
    TO_NUMBER(PRICE_TO_SELL)
FROM ITEMS_DATA;

-- FOOD TABLE
INSERT INTO FOOD (ID_FOOD, INGREDIENTS, ENERGY_REGAIN, HEALTH_REGAIN)
SELECT DISTINCT
   TO_NUMBER(ID),
   INGREDIENTS,
   TO_NUMBER(ENERGY),
   TO_NUMBER(HEALTH)
FROM ITEMS_DATA
WHERE INGREDIENTS IS NOT NULL AND ENERGY IS NOT NULL AND HEALTH IS NOT NULL;

-- SEED TABLE
INSERT INTO SEED (ID_SEED, SEED_TYPE, NAME_CROP)
SELECT
   TO_NUMBER(ID),
   TYPE,
   NAME_CROP
FROM ITEMS_DATA
WHERE NAME_CROP IS NOT NULL;

-- SUPPLY TABLE
INSERT INTO SUPPLY (ID_SUPPLY, NUTRITIONAL_VALUE, NUTRITIONAL_QUALITIES)
SELECT
   TO_NUMBER(ID),
   TO_NUMBER(NUTRITIONAL_VALUE),
   QUALITY
FROM ITEMS_DATA
WHERE NUTRITIONAL_VALUE IS NOT NULL
 AND QUALITY IS NOT NULL
 AND NOT EXISTS (
     SELECT 1 FROM SUPPLY s
     WHERE s.ID_SUPPLY = TO_NUMBER(ITEMS_DATA.ID)
 );

-- ANIMAL SPECIE TABLE
INSERT INTO ANIMAL_SPECIE (ID_ANIMAL_SPECIE, SPECIE_NAME)
SELECT ROWNUM, SPECIE_NAME
FROM (
   SELECT DISTINCT ANIMAL_SPECIE AS SPECIE_NAME FROM ITEMS_DATA WHERE ANIMAL_SPECIE IS NOT NULL
   UNION
   SELECT DISTINCT ANIMAL_SPECIE AS SPECIE_NAME FROM ANIMALS_PRODUCTS WHERE ANIMAL_SPECIE IS NOT NULL
);


-- PLACE TABLE 
INSERT INTO PLACE (
 ID_PLACE,
 LOCATION_NAME,
 COORDINATES,
 DESCRIPTION
)
SELECT
 ROWNUM   AS ID_PLACE,
 LOCATION_NAME,
 COORDINATES,
 DESCRIPTION
FROM (
 -- 1) from festivity shops 
 SELECT DISTINCT
   LOCATION_NAME,
   COORDENATES AS COORDINATES,
   DESCRIPTION
 FROM FESTIVITY_SHOPS
 WHERE LOCATION_NAME IS NOT NULL
   AND COORDENATES   IS NOT NULL
 UNION
 -- 2) from festivity persons
 SELECT DISTINCT
   LOCATION_NAME,
   COORDENATES AS COORDINATES,
   DESCRIPTION
 FROM FESTIVITY_PERSONS
 WHERE LOCATION_NAME IS NOT NULL
   AND COORDENATES   IS NOT NULL
 UNION
 -- 3) from events 
 SELECT DISTINCT
   LOCATION_NAME,
   COORDENATES AS COORDINATES,
   DESCRIPTION
 FROM EVENTS
 WHERE LOCATION_NAME IS NOT NULL
   AND COORDENATES   IS NOT NULL
 UNION
 -- 4) from schedules 
 SELECT DISTINCT
   LOCATION_NAME,
   COORDENATES AS COORDINATES,
   NULL
 FROM SCHEDULES
 WHERE LOCATION_NAME IS NOT NULL
   AND COORDENATES   IS NOT NULL
);  



-- Character (PLAYER_IDs only)
INSERT INTO CHARACTER (
  ID_CHARACTER,
  NAME,
  AGE,
  GENDER,
  ID_VILLAGE
)
SELECT
  TO_NUMBER(ID) AS ID_CHARACTER,
  NAME,
  TO_NUMBER(AGE) AS AGE,
  GENDER,
  NULL AS ID_VILLAGE  -- Your peer will populate this
FROM (
  -- Keep only the first occurrence of each ID
  SELECT pd.*,
    ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ROWNUM) as rn
  FROM PLAYER_DATA pd
) filtered
WHERE filtered.rn = 1;  -- Only keeping unique IDs, no limit


-- PLAYER
INSERT INTO PLAYER (
  ID_PLAYER,
  AVATAR_APPEARANCE,
  NICKNAME,
  GOLD,
  EXPERIENCE,
  SKILL,
  SKILL_LEVEL,
  ID_INVENTORY
)
SELECT
  TO_NUMBER(ID) AS ID_PLAYER,
  APPARENCE AS AVATAR_APPEARANCE,
  NICKNAME,
  TO_NUMBER(GOLD) AS GOLD,
  TO_NUMBER(EXPERIENCE) AS EXPERIENCE,
  SKILL,
  TO_NUMBER(SKILL_LEVEL) AS SKILL_LEVEL,
  inv.ID_INVENTORY
FROM (
  -- Get unique player entries with a row number
  SELECT pd.*,
    ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ROWNUM) as rn
  FROM PLAYER_DATA pd
) filtered
JOIN (
  -- Get all inventory IDs with a row number
  SELECT ID_INVENTORY, 
         ROWNUM as inventory_row_num
  FROM INVENTORY
) inv ON filtered.rn = inv.inventory_row_num
WHERE filtered.rn = 1;  -- Only keep unique IDs


-- SHOP table
INSERT INTO SHOP (
  ID_SHOP,
  NAME_SHOP,
  ID_PLACE,
  ID_INVENTORY
)
SELECT
  shop_data.ID_SHOP,
  shop_data.NAME_SHOP,
  shop_data.ID_PLACE,
  (next_inventory_id + ROWNUM - 1) AS ID_INVENTORY
FROM (
  -- Union all unique shop IDs from both sources
  SELECT 
    s.ID_SHOP,
    COALESCE(t.NAME, 'Shop #' || s.ID_SHOP) AS NAME_SHOP,
    (SELECT MIN(ID_PLACE) 
     FROM PLACE 
     WHERE LOCATION_NAME = s.LOCATION_NAME
     AND (COORDINATES = s.COORDINATES OR (COORDINATES IS NULL AND s.COORDINATES IS NULL))
    ) AS ID_PLACE,
    ROW_NUMBER() OVER (PARTITION BY s.ID_SHOP ORDER BY s.ID_SHOP) AS rn
  FROM (
    -- Get all unique shops from both sources
    SELECT ID_SHOP, LOCATION_NAME, COORDENATES AS COORDINATES
    FROM FESTIVITY_SHOPS 
    WHERE ID_SHOP IS NOT NULL
    
    UNION
    
    -- For shops only in TRANSACTIONS, use LOCATION_NAME from TRANSACTIONS
    SELECT 
      t.ID_SHOP, 
      t.LOCATION_NAME, 
      NULL AS COORDINATES
    FROM TRANSACTIONS t
    WHERE t.ID_SHOP IS NOT NULL
    AND NOT EXISTS (
      SELECT 1 FROM FESTIVITY_SHOPS fs 
      WHERE fs.ID_SHOP = t.ID_SHOP
    )
  ) s
  LEFT JOIN (
    -- Get names from TRANSACTIONS
    SELECT 
      ID_SHOP,
      MAX(NAME) AS NAME
    FROM TRANSACTIONS
    GROUP BY ID_SHOP
  ) t ON s.ID_SHOP = t.ID_SHOP
) shop_data,
(
  -- Subquery for next inventory ID
  SELECT CASE 
         WHEN MAX(ID_INVENTORY) IS NULL THEN 1 
         ELSE MAX(ID_INVENTORY) + 1 
         END AS next_inventory_id 
  FROM (
    SELECT ID_INVENTORY FROM PLAYER
    UNION
    SELECT ID_INVENTORY FROM SHOP
  )
) inventory_data
WHERE shop_data.rn = 1
AND NOT EXISTS (SELECT 1 FROM SHOP WHERE ID_SHOP = shop_data.ID_SHOP);

--INSERTING BUILDING FROM FARMS.CSV
INSERT INTO BUILDING (
  ID_BUILDING,
  NAME_BUILDING,
  DESCRIPTION,
  ID_PLACE
)
SELECT
  TO_NUMBER(ID_FARM) AS ID_BUILDING,
  'Building #' || ID_FARM AS NAME_BUILDING,
  'This is a building for farm #' || ID_FARM AS DESCRIPTION,
  (
    SELECT ID_PLACE
    FROM PLACE p
    WHERE p.LOCATION_NAME = f.LOCATION_NAME
    AND ROWNUM = 1
  ) AS ID_PLACE
FROM (
  SELECT ID_FARM, LOCATION_NAME,
         ROW_NUMBER() OVER (PARTITION BY ID_FARM ORDER BY ROWNUM) AS rn
  FROM FARMS
  WHERE ID_FARM IS NOT NULL AND LOCATION_NAME IS NOT NULL
) f
WHERE f.rn = 1
  AND NOT EXISTS (
    SELECT 1 FROM BUILDING b WHERE b.ID_BUILDING = TO_NUMBER(f.ID_FARM)
  );


--inserting Farms in Building from Player_Data.csv
INSERT INTO BUILDING (
  ID_BUILDING,
  NAME_BUILDING,
  DESCRIPTION,
  ID_PLACE
)
SELECT
  TO_NUMBER(ID_FARM),
  'Building from player_data #' || ID_FARM,
  'Auto-created from PLAYER_DATA',
  NULL
FROM (
  SELECT DISTINCT ID_FARM
  FROM PLAYER_DATA
  WHERE ID_FARM IS NOT NULL
) pd
WHERE NOT EXISTS (
  SELECT 1 FROM BUILDING b WHERE b.ID_BUILDING = TO_NUMBER(pd.ID_FARM)
);

--INSERTING INTO FARM FROM PLAYER_DATA.CSV
INSERT INTO FARM (
  ID_FARM,
  HECTARES,
  SPECIALIZATION,
  ID_PLAYER
)
SELECT
  TO_NUMBER(f.ID_FARM),
  TO_NUMBER(f.HECTARES),
  f.SPECIALIZATION,
  TO_NUMBER(f.ID) AS ID_PLAYER
FROM (
  SELECT 
    ID_FARM,
    HECTARES,
    SPECIALIZATION,
    ID,
    ROW_NUMBER() OVER (PARTITION BY ID_FARM ORDER BY ROWNUM) AS rn
  FROM PLAYER_DATA
  WHERE ID_FARM IS NOT NULL 
    AND HECTARES IS NOT NULL 
    AND SPECIALIZATION IS NOT NULL
) f
WHERE f.rn = 1
  AND NOT EXISTS (
    SELECT 1 FROM FARM ff WHERE ff.ID_FARM = TO_NUMBER(f.ID_FARM)
  );

--INSERTING INTO FARM FROM FARMS.CSV
INSERT INTO FARM (
  ID_FARM,
  HECTARES,
  SPECIALIZATION,
  ID_PLAYER
)
SELECT
  id_farm_num,
  --DEFAULT VALUE GENERATED
  1.0 AS HECTARES,
  'General' AS SPECIALIZATION,
  NULL AS ID_PLAYER
FROM (
  SELECT DISTINCT TO_NUMBER(ID_FARM) AS id_farm_num
  FROM FARMS
  WHERE ID_FARM IS NOT NULL
) f
WHERE f.id_farm_num NOT IN (SELECT ID_FARM FROM FARM);

--TODO ASK IF THIS IS OKAY TO UPDATE AND CHECK POSSIBLE RELATIONS
UPDATE FARM f
SET ID_PLAYER = (
  SELECT TO_NUMBER(pd.ID)
  FROM PLAYER_DATA pd
  WHERE TO_NUMBER(pd.ID_FARM) = f.ID_FARM
    AND TO_NUMBER(pd.ID) IN (SELECT ID_PLAYER FROM PLAYER)
    AND ROWNUM = 1
)
WHERE f.ID_PLAYER IS NULL
  AND EXISTS (
    SELECT 1
    FROM PLAYER_DATA pd
    WHERE TO_NUMBER(pd.ID_FARM) = f.ID_FARM
      AND TO_NUMBER(pd.ID) IN (SELECT ID_PLAYER FROM PLAYER)
  );

--INSERTING INTO FARMBUILDING FROM FARMS.CSV
INSERT INTO FARMBUILDING (
  ID_FARM_BUILDING,
  NAME_BUILDING,
  DESCRIPTION,
  BUILDING_SIZE,
  ID_FARM
)
SELECT
  TO_NUMBER(f.ID) AS ID_FARM_BUILDING,
  f.NAME,
  f.DESCRIPTION,
  TO_NUMBER(f.BUILDING_SIZE),
  TO_NUMBER(f.ID_FARM)
FROM (
  SELECT 
    ID,
    NAME,
    DESCRIPTION,
    BUILDING_SIZE,
    ID_FARM,
    ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ROWNUM) AS rn
  FROM FARMS
  WHERE ID IS NOT NULL
    AND NAME IS NOT NULL
    AND BUILDING_SIZE IS NOT NULL
    AND ID_FARM IS NOT NULL
) f
WHERE f.rn = 1
  AND EXISTS (
    SELECT 1 FROM FARM fa WHERE fa.ID_FARM = TO_NUMBER(f.ID_FARM)
  )
  AND NOT EXISTS (
    SELECT 1 FROM FARMBUILDING fb WHERE fb.ID_FARM_BUILDING = TO_NUMBER(f.ID)
  );

--INSERTING INTO BARN FROM FARMS.CSV
INSERT INTO BARN (
  ID_BARN,
  MAX_CAPACITY,
  OCCUPIED_SPOTS
)
SELECT
  TO_NUMBER(f.ID) AS ID_BARN,
  TO_NUMBER(f.CAPACITY) AS MAX_CAPACITY,
  TO_NUMBER(f.OCCUPIED_SPOTS) AS OCCUPIED_SPOTS
FROM (
  SELECT 
    ID,
    CAPACITY,
    OCCUPIED_SPOTS,
    ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ROWNUM) AS rn
  FROM FARMS
  WHERE ID IS NOT NULL AND CAPACITY IS NOT NULL AND OCCUPIED_SPOTS IS NOT NULL
) f
WHERE f.rn = 1
  AND EXISTS (
    SELECT 1 FROM FARMBUILDING fb WHERE fb.ID_FARM_BUILDING = TO_NUMBER(f.ID)
  )
  AND NOT EXISTS (
    SELECT 1 FROM BARN b WHERE b.ID_BARN = TO_NUMBER(f.ID)
  );

--INSERT INTO ANIMAL FROM ANIMALS_PRODUCTS.CSV
INSERT INTO ANIMAL (
  ID_ANIMAL,
  NAME_ANIMAL,
  AGE,
  ID_ANIMAL_SPECIE,
  HEALTH,
  ID_BARN,
  QUANTITY
)
SELECT
  TO_NUMBER(ap.ID) AS ID_ANIMAL,
  ap.NAME,
  TO_NUMBER(ap.AGE),
  s.ID_ANIMAL_SPECIE, 
  ap.HEALTH_STATUS,
  CASE 
    WHEN ap.ID_BARN_BUILDING IS NOT NULL THEN TO_NUMBER(ap.ID_BARN_BUILDING)
    ELSE NULL
  END AS ID_BARN,
  1 AS QUANTITY
FROM (
  SELECT 
    ID,
    NAME,
    AGE,
    HEALTH_STATUS,
    ANIMAL_SPECIE,
    ID_BARN_BUILDING,
    ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ROWNUM) AS rn
  FROM ANIMALS_PRODUCTS
  WHERE 
    ID IS NOT NULL AND
    NAME IS NOT NULL AND
    AGE IS NOT NULL AND
    HEALTH_STATUS IS NOT NULL AND
    ANIMAL_SPECIE IS NOT NULL
) ap
LEFT JOIN ANIMAL_SPECIE s
  ON s.SPECIE_NAME = ap.ANIMAL_SPECIE
WHERE ap.rn = 1
  AND NOT EXISTS (
    SELECT 1 FROM ANIMAL an WHERE an.ID_ANIMAL = TO_NUMBER(ap.ID)
  );

--TO RANDOM GENERATE FOR PRODUCT ID
CREATE SEQUENCE SEQ_PRODUCT_ID START WITH 1000 INCREMENT BY 1

--insert into product from animal_products.csv
INSERT INTO PRODUCT (
  ID_PRODUCT,
  NAME_PRODUCT,
  ID_ANIMAL_SPECIE
)
SELECT
  SEQ_PRODUCT_ID.NEXTVAL AS ID_PRODUCT,
  ap.PRODUCT AS NAME_PRODUCT,
  s.ID_ANIMAL_SPECIE
FROM (
  SELECT 
    PRODUCT,
    ANIMAL_SPECIE,
    ROW_NUMBER() OVER (PARTITION BY PRODUCT ORDER BY ROWNUM) AS rn
  FROM ANIMALS_PRODUCTS
  WHERE 
    PRODUCT IS NOT NULL AND 
    ANIMAL_SPECIE IS NOT NULL
) ap
JOIN ANIMAL_SPECIE s
  ON s.SPECIE_NAME = ap.ANIMAL_SPECIE
WHERE ap.rn = 1
  AND NOT EXISTS (
    SELECT 1 FROM PRODUCT p WHERE p.NAME_PRODUCT = ap.PRODUCT
  );

--INSERT INTO PRODUCE FROM ANIMAL, PRODUCT TABLES AND ANIMALS_PRODUCT.CSV (QUALITY)
INSERT INTO PRODUCE (
  ID_ANIMAL,
  ID_PRODUCT,
  PRODUCTION_DATE,
  EXPIRATION_DATE,
  QUALITY
)
SELECT
  TO_NUMBER(ap.ID) AS ID_ANIMAL,
  p.ID_PRODUCT,
  TRUNC(SYSDATE - DBMS_RANDOM.VALUE(0, 30)) AS PRODUCTION_DATE,
  TRUNC(SYSDATE + DBMS_RANDOM.VALUE(30, 90)) AS EXPIRATION_DATE,
  ap.QUALITY
FROM (
  SELECT 
    ID,
    PRODUCT,
    QUALITY,
    ROW_NUMBER() OVER (PARTITION BY ID, PRODUCT ORDER BY ROWNUM) AS rn
  FROM ANIMALS_PRODUCTS
  WHERE 
    ID IS NOT NULL AND 
    PRODUCT IS NOT NULL AND 
    QUALITY IS NOT NULL
) ap
JOIN ANIMAL a ON TO_NUMBER(ap.ID) = a.ID_ANIMAL
JOIN PRODUCT p ON p.NAME_PRODUCT = ap.PRODUCT
WHERE ap.rn = 1
  AND NOT EXISTS (
    SELECT 1 
    FROM PRODUCE pr 
    WHERE pr.ID_ANIMAL = TO_NUMBER(ap.ID)
      AND pr.ID_PRODUCT = p.ID_PRODUCT
  );

--INSERT INTO CULTIVATIONFIELD FROM FARMS.CSV
INSERT INTO CULTIVATIONFIELD (
  ID_FIELD,
  COST,
  STATE
)
SELECT
  TO_NUMBER(f.ID) AS ID_FIELD,
  TO_NUMBER(f.BUILDING_COST) AS COST,
  f.STATUS AS STATE
FROM (
  SELECT 
    ID,
    BUILDING_COST,
    STATUS,
    ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ROWNUM) AS rn
  FROM FARMS
  WHERE 
    ID IS NOT NULL AND 
    BUILDING_COST IS NOT NULL AND 
    STATUS IS NOT NULL
) f
INNER JOIN FARMBUILDING fb
  ON TO_NUMBER(f.ID) = fb.ID_FARM_BUILDING
WHERE f.rn = 1
  AND NOT EXISTS (
    SELECT 1 FROM CULTIVATIONFIELD cf WHERE cf.ID_FIELD = TO_NUMBER(f.ID)
  );

--TO AUTOGENERATE THE ID FOR ID_CROP
CREATE SEQUENCE SEQ_CROP_ID START WITH 1000 INCREMENT BY 1;

--INSERT INTO CROP FROM THE FARMS.CSV
INSERT INTO CROP (
  ID_CROP,
  NAME_CROP,
  GROWING_SEASON,
  GROWTH_DURATION,
  QUALITY
)
SELECT
  SEQ_CROP_ID.NEXTVAL AS ID_CROP,
  f.CROP AS NAME_CROP,
  f.SEASON_NAME AS GROWING_SEASON,
  TO_NUMBER(f.GROWTH_TIME) AS GROWTH_DURATION,
  f.QUALITY
FROM (
  SELECT 
    CROP,
    SEASON_NAME,
    GROWTH_TIME,
    QUALITY,
    ROW_NUMBER() OVER (PARTITION BY CROP ORDER BY ROWNUM) AS rn
  FROM FARMS
  WHERE 
    CROP IS NOT NULL AND 
    SEASON_NAME IS NOT NULL AND 
    GROWTH_TIME IS NOT NULL AND 
    QUALITY IS NOT NULL
) f
WHERE f.rn = 1
  AND NOT EXISTS (
    SELECT 1 FROM CROP c WHERE c.NAME_CROP = f.CROP
  );


--INSERT INTO GROW FROM THE CULTIVATION FIELD AND CROP TABLES
INSERT INTO GROW (
  ID_FIELD,
  ID_CROP
)
SELECT
  TO_NUMBER(f.ID) AS ID_FIELD,
  c.ID_CROP
FROM FARMS f
JOIN CROP c ON c.NAME_CROP = f.CROP
WHERE 
  f.ID IS NOT NULL AND 
  f.CROP IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM GROW g
    WHERE g.ID_FIELD = TO_NUMBER(f.ID)
      AND g.ID_CROP = c.ID_CROP
  );
